id: A9DDA1989
title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life of His
  Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One by Jamyang
  Khyentse Chökyi Lodrö'
type: translation
pechas:
- I1E1D1F41
- I4BAA25A6
- IEB9AB3A1
- IE1310B7B
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:44.095870
  last_modified_at: 2023-01-04 11:53:44.095875
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I1E1D1F41/D843: 2BA5
  I4BAA25A6/5411: 2BA5
  IEB9AB3A1/97C6: 2BA5
  IE1310B7B/E710: 2BA5
